//
// client.c
//
// Created by Baturalp KIZILTAN on 6.10.2021.
//

#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

#include "model.h"

#define SIN_PORT 4444

void fatal(const char *);

int main(void)
{
    struct sockaddr_in sockaddr;

    printf("setting up socket address\n");
    memset(&sockaddr, 0, sizeof sockaddr); // Initialize with 0
    sockaddr.sin_family = AF_INET;
    sockaddr.sin_port = htons(SIN_PORT);
    if (inet_pton(AF_INET, "127.0.0.1", &sockaddr.sin_addr) != 1)
    {
        fatal("network address conversion failed");
    }

    int sockfd;
    printf("setting up socket file descriptor\n");
    if ((sockfd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)) == -1)
    {
        fatal("socket file descriptor creation failed");
    }

    printf("connecting to server\n");
    if (connect(sockfd, (const struct sockaddr *) &sockaddr, sizeof sockaddr) == -1)
    {
        fatal("socket connection failed");
    }

    // Send message
    printf("sending message\n");
    struct message new_msg;
    generate_new_message(&new_msg, "Client", /*"EXIT"*/ "This message's generated by client.");

    if (send_message_as_whole(sockfd, &new_msg, sizeof new_msg) == -1)
    {
        close(sockfd);
        fatal("message sending failed");
    }

    // Read message
    printf("reading message\n");
    struct message buffer;
    if (recv(sockfd, &buffer, sizeof (struct message), 0) == -1)
    {
        close(sockfd);
        fatal("cannot read received message");
    }
    pretty_print_message(&buffer);

    printf("done, exiting..!\n");
    close(sockfd);
    return 0;
}

void fatal(const char *msg)
{
    perror(msg);
    printf("ERRNO: %d", errno);
    exit(1);
}
